### ISSUE TITLE
Discrepancy between data preparation code and paper

### ISSUE THREAD

**Issue by yx-chan131** [zyxxmu/DDA#1]
Hi, 

I would like to reproduce your result on FHDMi dataset. I'm reading the data preparation code and found that there are some discrepancies between paper and provided code.

1. In the paper's implementation details, FHDMi images are said to be cropped into patches of size 640x540, but in the code they are cropped to size 512x480.
2. The original resolution of FHDMi is 1920x1080, but in the code the images are resized to 1920x1024 before cropping. Would you mind to explain the reasoning behind the operation?

Thanks. Looking forward to hearing from you soon.

**Comment by lixcli** [comment]
Thanks for your interest of our work. 
1. Only the images of aim19 are cropped into patches of size 512x480, while the patches of FHDMI is 640x512. Maybe there is a misunderstood here.
2. The example networks(MBCNN & DMCNN) are multi-scale with 3 branches so that the resolution of patch need to be divisible by 16. The closest and suitable resolution  is 1920x1024.

**Comment by yx-chan131** [comment]
Hi, thanks for your prompt reply.

1. Line 29 of data_script/fhdmi/slit_patches_train.py defines crop size as (480, 512). Perhaps you forgot to update it.
2. Understood, thanks.

There are some other questions I would like to ask as well:
1. In run/mbcnn_fhdmi.sh, the model is trained in two stages, why are the patch size of the 2 stages different (192 and 384 respectively)?
2. I would like to test model without DDA setting (e.g., MBCNN), can I use the same test script or is there any changes I should make?
Thanks.

**Comment by lixcli** [comment]
Hi, 
1. Accordding to the paper setting, MBCNN need two stage training, you can refer the Sec4.1 of "Image Demoireing with Learnable Bandpass Filters"
2. You may need to remove the data preparing of DDA and change the training script. Or you can try the other MBCNN implemetations :). For example, [MBCNN_torch_demoire](https://github.com/JunghyunKim242/MBCNN_torch_demoire)
